cc_library(
    name="tokme",
    srcs=[
        "youtokentome/cpp/bpe.cpp",
        "youtokentome/cpp/utils.cpp",
        "youtokentome/cpp/utils.h",
        "youtokentome/cpp/utf8.cpp",
        "youtokentome/cpp/utf8.h",
        "youtokentome/cpp/special_token_lexer.cpp",
        "youtokentome/cpp/special_token_lexer.h",
        "youtokentome/cpp/third_party/flat_hash_map.h",
    ],
    hdrs=[
        "youtokentome/cpp/bpe.h",
    ]
)